### ISSUE TITLE
breaks ES6 multiple imports

### ISSUE THREAD

**Issue by drzraf** [yggie/babel-plugin-inline-json-import#12]
Using 0.3.1:

One of my files is doing:
`import { a, b } from './foo.js';`

Plugin breaks compilation with:

```
Error: don't know how to turn this value into a node
    at valueToNode (proj/node_modules/@babel/types/lib/converters/valueToNode.js:103:9)
    at Object.valueToNode (proj/node_modules/@babel/types/lib/converters/valueToNode.js:97:58)
    at proj/node_modules/babel-plugin-inline-json-import/build/index.js:55:61
    at Array.map (<anonymous>)
    at PluginPass.exit (proj/node_modules/babel-plugin-inline-json-import/build/index.js:46:50)
    at newFn (proj/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (proj/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (proj/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (proj/node_modules/@babel/traverse/lib/path/context.js:97:8)
    at TraversalContext.visitQueue (proj/node_modules/@babel/traverse/lib/context.js:118:16)
```

More specifically the line:
`if (init != null && init.type === 'CallExpression' && init.callee.type === 'Identifier' && init.callee.name === 'require' && init.arguments.length === 1 && init.arguments[0].type === 'StringLiteral') { ... }`

Dumping `init`:
```
{ type: 'CallExpression',
  callee: { type: 'Identifier', name: 'require' },
  arguments: [ { type: 'StringLiteral', value: './foo.js' } ] }
```

It's was really hard to spot the error came from this module. Hopefully it could be fixed/released soon.

**Comment by ordoghl** [comment]
Maybe similar case:

After upgrading from 0.2.1 to 0.3.1 babel 7.2.2 throws:

```
(function (exports, require, module, __filename, __dirname) { import { DATABASE_URL, LOG_SQL } from '../config'
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by id-matt-michler** [comment]
I ran into this as well except a different error.

`import { anything } from 'module'`
Would result in 
`Error: Cannot find module '/path/to/project/src/module'`

Changing the import code to `import * as mod from 'module'` works as intended

**Comment by drzraf** [comment]
@yggie?

**Comment by yggie** [comment]
@drzraf sorry I meant to get back to you sooner but the issue just fell off my radar!

After some debugging and attempts at replicating the issue, I think I found what could be causing the problem. The latest patch `v0.3.2` contains a potential fix for the issue, the same module check is not being applied for variable declarations as opposed to imports, which is why it tries to parse non-JSON files and the result is the above failure when it encounters a non-JSON file. If this solves your problem, feel free to close the issue.

On a different note, your case in particular is a bit troubling, it doesn’t quite fall into what I consider as the cause of the issue, however you could also have other webpack plugins that could be transforming the code before it gets to my plugin. The error message is the same in the test case I used when reproducing the error based on the other comments on the issue. If the latest patch does not solve your issue, please share what you can about your webpack configuration that could be affecting the plugin, and I will try to find a way to patch this up from my side.

**Comment by drzraf** [comment]
Yes! That made it! Thank you!
